(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.trykher1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#33CC33").s().p("AEoEiQgZAAgNgHQgOgIgFgSQgDgJgDgUIgCgXQgDgTgPAAIgHAAIAABLQABAMADADQADADAPABIAAAKIh1AAIAAgKQAOgBADgDQADgDAAgMIAAihQAAgNgDgDQgDgDgOgBIAAgKICEAAQAmgBAPAJQAXAMAAAgQAAAXgQAOQgSAPgjABIAAADQAfAGAPAQQAMAMAFAXQAFAcAFAIQAEAGANADIAAAKgADRBUQgCADgBAHIAABPIAHAAQAfAAAAguQAAgtgZAAQgIAAgCACgAhcEiIAAgKQAOgBADgDQADgDAAgMIAAihQAAgNgDgDQgDgDgOgBIAAgKIC0AAIAABAIgNAAQgQgkgHgIQgGgGgVAAIgLAAQgHAAgBACQgCABAAAJIAABLIALAAQAQgBAEgEQAFgFAJgYIAMAAIAABSIgMAAQgKgZgEgEQgEgFgQAAIgLAAIAABIQAAANADADQAEADARAAQAUAAAJgIQALgKAUgnIAMAAIgFBHgAjbEiIAAgKQAMgBACgCQADgCAAgMIAAhSIgxAAIAABSQAAALADADQACACAMABIAAAKIhzAAIAAgKQAOgBADgCQAEgEAAgKIAAimQAAgLgDgDQgEgDgOAAIAAgKIBzAAIAAAKQgMAAgCADQgDADAAALIAABGIAxAAIAAhGQAAgLgDgDQgCgDgMAAIAAgKIByAAIAAAKQgPAAgDADQgDACAAAMIAACmQAAAMAEACQADACAOABIAAAKgAGKhEQgZgBgOgHQgNgGgJgOQgOgYgTg0IAABKQAAAMACADQAEADAOAAIAAALIh2AAIAAgLQAOAAAEgDQACgDAAgMIAAiiQAAgMgCgDQgEgDgKAAQgIAAgEACQgFACgEAJQgaA2gTAxQgDAGAAAJIAAAxQAAAMAEADQAEACAUABIAAALIiAAAIAAgLQATgBAEgCQAEgDgBgMIAAguQAAgJgDgIQgfhGgUgkQgEgHgEgCQgCgCgKgBIAAgKIB7AAIAAAKIgQACQgGABAFAKIAlBYIABAAQAQgsANgqQAEgMgHgBIgRgCIAAgKICyAAIAAAKQgOABgEADQgCADAAAMIAABPQANgNAbggQAbgiAFgJQADgGgHgCIgRgCIAAgKIBTAAIAAAKQgYAEgMAJQgQAOgfAhQALAZAVAjQAVAmARAXQALAPAMAGIgCAKgAguhFQgZAAgNgHQgOgIgFgSQgEgJgCgUIgCgXQgDgTgPAAIgHAAIAABLQABAMADADQADADAOAAIAAALIh1AAIAAgLQAOAAAEgDQADgDAAgMIAAiiQAAgMgDgDQgEgDgOgBIAAgKICFAAQAlgBAQAJQAXAMAAAgQAAAXgQAOQgTAPghABIAAADQAeAGAPAQQANAMAEAWQAFAdAFAHQAEAHANACIAAALgAiFkTQgCADgBAHIAABPIAHAAQAfAAAAguQAAgtgaAAQgHAAgCACgAmZhFIAAgLQASAAAFgDQAFgDABgMIAAixIgKAAQgQAAgFAHQgGAJgLAlIgPAAIAAhDIDJAAIAABDIgOAAQgMglgGgIQgFgIgQAAIgKAAIAACxQABAMAFADQAFADATAAIAAALg");
	this.shape.setTransform(66,65.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFF00").s().p("AkcJLQg+gfg4guIgQgNQgVgSgTgTIgCgCQgdgdgYgfQgfgmgXgqQguhPgUhZQgQhHAAhPQAAivBSiOIAGgMQASgdAUgbIAKgMIAPgUQATgVAVgUQA0g1A6gmQAYgQAZgNQBmg1B2gOQAngEAoAAQBIAABCAOQBxAXBhA/QA7AmA1A1QAUAUASAVIAaAgQB+CnAADaQAAEMi9C+IgBACQgUATgVASIgPANQiuCMjmAAQiaAAiCg/gADeC8QAQAAACATIADAXQACAUADAJQAGASANAIQANAHAaAAIArAAIAAgKQgMgDgEgGQgFgIgFgcQgFgXgMgMQgQgQgegGIAAgDQAigBASgPQAQgOAAgXQABgggXgMQgQgJglABIiFAAIAAAKQAOABAEADQACADAAANIAAChQAAAMgCADQgEADgOABIAAAKIB1AAIAAgKQgPgBgDgDQgDgDAAgMIAAhLgAhTBSQAOABADADQAEADAAANIAAChQAAAMgEADQgDADgOABIAAAKIC7AAIAGhHIgMAAQgVAngLAKQgIAIgUAAQgSAAgDgDQgDgDgBgNIAAhIIALAAQAQAAAFAFQAEAEAJAZIANAAIAAhSIgNAAQgJAYgEAFQgFAEgQABIgLAAIAAhLQABgJABgBQACgCAGAAIAMAAQAVAAAGAHQAHAHAPAkIAOAAIAAhAIi1AAgAjBC3IAABSQAAAMgCACQgDACgMABIAAAKIByAAIAAgKQgOgBgDgCQgEgCABgMIAAimQAAgMACgCQADgDAPAAIAAgKIhyAAIAAAKQAMAAADADQACADAAALIAABGIgwAAIAAhGQgBgLADgDQADgDAMAAIAAgKIhzAAIAAAKQAOAAAEADQACADAAALIAACmQABAKgEAEQgEACgNABIAAAKIBzAAIAAgKQgMgBgDgCQgDgDABgLIAAhSgAFXheQAJAOAMAGQAOAHAaABIAwABIABgKQgLgGgLgPQgSgXgVgmQgUgjgLgZQAeghARgOQALgJAYgEIAAgKIhSAAIAAAKIARACQAHACgEAGQgEAJgbAiQgbAggOANIAAhPQAAgMACgDQAEgDAOgBIAAgKIixAAIAAAKIAQACQAIABgEAMQgNAqgQAsIgBAAIgmhYQgFgKAHgBIAPgCIAAgKIh6AAIAAAKQAIABAEACQADACAFAHQAUAkAfBGQADAIAAAJIAAAuQAAAMgEADQgEACgSABIAAALIB/AAIAAgLQgTgBgFgCQgEgDABgMIAAgxQAAgJACgGQATgxAag2QAEgJAFgCQAEgCAJAAQAKAAADADQADADAAAMIAACiQAAAMgDADQgEADgOAAIAAALIB2AAIAAgLQgOAAgEgDQgCgDAAgMIAAhKQAUA0AOAYgAh4irQAQAAACATIADAXQACAUADAJQAGASANAIQANAHAaAAIAqAAIAAgLQgLgCgEgHQgFgHgGgdQgEgWgMgMQgQgQgegGIAAgDQAigBASgPQAQgOAAgXQABgggXgMQgQgJglABIiFAAIAAAKQAOABAEADQACADAAAMIAACiQAAAMgCADQgEADgOAAIAAALIB1AAIAAgLQgPAAgDgDQgDgDAAgMIAAhLgAlzkRIAACxQAAAMgFADQgGADgSAAIAAALICGAAIAAgLQgSAAgFgDQgGgDAAgMIAAixIAKAAQAPAAAFAIQAHAIALAlIAPAAIAAhDIjKAAIAABDIAPAAQAMglAFgJQAGgHAPAAgADYCvIAAhPQAAgHACgDQACgCAIAAQAZAAABAtQAAAuggAAgAh+i4IAAhPQAAgHADgDQACgCAHAAQAZAAABAtQAAAuggAAg");
	this.shape_1.setTransform(65,65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,130,130);


(lib.trykher = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF00").s().p("AkxJ2QhCghg9gxIgGgFQgcgXgbgaIgBgCQgfgggaggQghgqgagsQgvhVgWhgQgShNAAhUQAAi8BXiZIAIgMQAWgmAdgjIARgWIAHgIQARgTARgSQA5g4A/gpQAZgQAbgOQBtg6B/gOQAqgFArAAQBNAABHAOQB6AZBoBEQA/ApA5A4IAiAlIAIAIQCiC/AAEBQAAEgjLDMIgBACQgbAagcAXIgGAFQi6CWj3AAQimAAiLhEgADuDJQARAAADAVIACAZQADAVADAKQAHATAOAIQAOAJAcAAIAuAAIAAgMQgNgDgFgGQgFgIgGggQgEgXgNgOQgSgRgggHIAAgCQAkgBATgRQASgPAAgYQAAgkgYgMQgRgJgoAAIiPAAIAAAMQAPAAAEADQADAEABANIAACtQgBANgDAEQgEADgPABIAAAMIB+AAIAAgMQgPgBgEgDQgEgEABgNIAAhQgAhZBYQAOAAAEADQADAEAAANIAACtQAAANgDAEQgEADgOABIAAAMIDIAAIAHhOIgNAAQgWAqgMALQgJAJgVAAQgUAAgDgDQgEgDAAgOIAAhOIAMAAQARABAEAFQAFAEAKAbIANAAIAAhYIgNAAQgJAZgGAGQgEAEgRABIgMAAIAAhRQAAgIACgDQACgCAHAAIAMAAQAWAAAHAIQAHAHARAnIAPAAIAAhFIjCAAgAjPDFIAABYQAAAMgDACQgDACgNABIAAAMIB7AAIAAgMQgQgBgDgDQgDgCgBgLIAAizQAAgMADgDQAEgDAQAAIAAgMIh7AAIAAAMQANAAADADQADADAAAMIAABLIg1AAIAAhLQAAgMACgDQAEgDAMAAIAAgMIh7AAIAAAMQAQAAADADQADADABAMIAACzQgBAKgDADQgEADgPABIAAAMIB7AAIAAgMQgNgBgCgDQgDgCAAgLIAAhYgAFMi3QAVA3APAbQAJAPAOAGQAPAIAbAAIA0ACIACgLQgMgGgNgRQgSgYgXgpQgWgmgMgbQAhgjASgPQANgKAZgEIAAgLIhZAAIAAALIASACQAIABgDAIQgGAKgdAjQgdAjgOANIAAAAIAAhTQAAgNACgEQAFgDAOgBIAAgLIi+AAIAAALIARACQAIABgEANQgOAtgSAvIAAAAIgpheQgFgLAIgBIAQgCIAAgLIiDAAIAAALQAIABAEACQAEADAEAHQAWAmAiBMQADAIAAAJIAAAyQAAANgEADQgEADgUABIAAAMICIAAIAAgMQgUgBgFgDQgEgDAAgNIAAg0QAAgKADgHQAUg0Acg6QAEgJAGgDQADgCALAAQALAAACADQAEAEAAANIAACsQAAAOgEADQgDADgPABIAAAMIB+AAIAAgMQgPgBgEgDQgCgDAAgOIAAhOgAiBi5QARABACAUIADAaQACAUAEAKQAGAUAOAIQAOAIAcAAIAtAAIAAgMQgMgCgEgHQgGgIgFgfQgFgYgNgOQgRgRghgGIAAgDQAkgBAUgRQARgPAAgYQAAgjgXgMQgSgJgoAAIiOAAIAAALQAPABADADQAEAEAAANIAACsQAAAOgEADQgDADgPABIAAAMIB9AAIAAgMQgPgBgEgDQgDgDAAgOIAAhQgAmOkmIAAC9QgBANgGAEQgFADgUABIAAAMICQAAIAAgMQgTgBgGgDQgGgEAAgNIAAi9IALAAQAQABAGAHQAGAKANAoIAPAAIAAhJIjYAAIAABJIAQAAQAMgpAHgJQAFgHAQgBg");
	this.shape.setTransform(69.8,69.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,139.6,139.6);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#59AE40").s().p("Ag5CjQgagRAAgfIAAjgQAAgiATgQQAWgSAvAAQApAAAVASQARAQAAAcIAAA/IhFAAIAAhGQAAgEgDgCIgIgCIgIACQgDACAAAEIAADzQAAAEAEACIAHADQAGAAACgDQADgCAAgEIAAhXIBFAAIAABZQAAAVgUAQQgXASgkAAQgmAAgYgPg");
	this.shape.setTransform(100.5,28.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E12B2B").s().p("AF8CnQgNgLAAgWIAAg5QAAgiAugXQAvgVAAgJIAAgqQAAgHgDgEQgDgDgFAAQgFAAgEADQgDAEAAAHIAAA3IhEAAIAAg4QAAgfAagPQAUgLAlAAQAlAAATAMQAWAPAAAhIAADgIg+AAIAAgLQgFAKgKACQgKADgTAAQgfAAgNgLgAG5A5QgFAFAAAIIAAAzQAAAHAEADQADADAGAAQAFAAADgDQADgDAAgHIAAhJQgOAEgFAFgAhHCnQgNgLAAgWIAAg5QAAgiAvgXQAugVAAgJIAAgqQAAgHgDgEQgDgDgFAAQgFAAgDADQgEAEAAAHIAAA3IhDAAIAAg4QAAgfAZgPQAVgLAkAAQAlAAASAMQAWAPAAAhIAADgIg9AAIAAgLQgFAKgLACQgJADgTAAQgfAAgNgLgAgJA5QgFAFAAAIIAAAzQAAAHADADQADADAGAAQAEAAAEgDQADgDAAgHIAAhJQgNAEgFAFgAjACtIgMgIIgGAJIg1AAIAAldIBGAAIAABLQAGgFALgDIAagCQAWAAAOALQAOAMAAAQIAADLQAAARgPAOQgSAPgfAAQgRAAgLgFgAi+g/QgDADAAAGIAACvQAAAHADADQADADAGAAQAGAAADgDQADgDAAgHIAAiuQAAgNgMAAQgGAAgDADgAmeCmQgYgPAAghIAAioQAAggAYgPQAVgNAlAAQAiAAAXAOQAYAPAAAcIAACuQAAAggYAOQgUALglAAQglAAgVgMgAltg/QgEAEAAAHIAACsQAAAHADAEQADADAGAAQAGAAADgDQADgEAAgHIAAisQAAgHgDgEQgDgDgGAAQgFAAgDADgAqvClQgWgQAAgfIAAjjQAAgiASgQQAVgSAwAAQAqAAAVASQATARAAAbIAABBIhFAAIAAhIQAAgEgDgCIgJgCIgJACQgDACAAAEIAADzQAAAEAEACIAIADIAIgCQAEgDAAgEIAAhCIgRAAIAAg1IBWAAIAACsIglAAIgKgSQgMALgIAEQgPAHgSAAQgdAAgSgNgAIjCuIAAkaIBGAAIAAAJQAGgFALgDQALgDAPAAQAWAAAOAMQAOALAAARIAABOIhFAAIAAg9QAAgNgMAAQgGAAgDADQgDADAAAHIAADjgABfCuIAAldIBGAAIAAFdgAoMCuIAAldIBFAAIAAFdg");
	this.shape_1.setTransform(73.9,28.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(2.9,10.8,142,35.7), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAQQgHgHAAgJQAAgJAHgGQAHgGAIAAQAKAAAGAGQAHAGAAAJQAAAJgHAHQgGAGgKABQgIgBgHgGg");
	this.shape.setTransform(124.6,55.4,0.914,0.914);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgPAQQgHgHAAgJQAAgJAHgGQAGgGAJAAQAJAAAHAGQAHAGAAAJQAAAJgHAHQgHAGgJABQgJgBgGgGg");
	this.shape_1.setTransform(19.2,55.4,0.914,0.914);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#020203").s().p("Ag9A+QgagaAAgkQAAgjAagaQAagaAjAAQAlAAAZAaQAaAaAAAjQAAAkgaAaQgZAaglAAQgjAAgagag");
	this.shape_2.setTransform(124.6,55.4,0.914,0.914);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhPBQQgighAAgvQAAguAighQAhgiAuABQAvgBAhAiQAiAhAAAuQAAAvgiAhQghAigvAAQguAAghgig");
	this.shape_3.setTransform(124.6,55.4,0.914,0.914);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#020203").s().p("AhsBsQgtgtAAg/QAAg+AtguQAtgsA/gBQBAABAtAsQAtAuAAA+QAAA/gtAtQgtAuhAgBQg/ABgtgug");
	this.shape_4.setTransform(124.6,55.4,0.914,0.914);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#020203").s().p("Ag9A+QgagaAAgkQAAgjAagaQAZgaAkAAQAkAAAaAaQAaAaAAAjQAAAkgaAaQgaAagkAAQgkAAgZgag");
	this.shape_5.setTransform(19.2,55.4,0.914,0.914);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhPBQQgighAAgvQAAguAighQAhgiAuABQAvgBAhAiQAiAhAAAuQAAAvgiAhQghAigvAAQguAAghgig");
	this.shape_6.setTransform(19.2,55.4,0.914,0.914);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#020203").s().p("AgkAJQgDAAgDgDQgDgDAAgDQAAgIANAAIBJAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAABQACADAAACQABAJgJAAg");
	this.shape_7.setTransform(82.1,28.6,0.914,0.914);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#020203").p("AETjDIAAGCIgJArQgRArguAAImhAAQglAAgOgsIgIgrQgDhaALhTQAEgfAWguQALgXAUgiQARgdAAgBQAWgiAeggQA5g8AvgDIDlAAQAiAAAXAYQAYAXAAAig");
	this.shape_8.setTransform(63.6,30.1,0.914,0.914);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#59AE40").s().p("Al/gSIgcgPIM3AAQgIAPgLAxIrVADQgTgegggWg");
	this.shape_9.setTransform(63.7,44.5,0.914,0.914);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ApLCdQgIAAgLgKQgVgVgQg0QgGgUgKgPILWgDQACgwAlgxQBJhiCrADQCEADBaA/QAtAfASAfIAOAoQAOAygEApQgDAbgiAIIhVADQgLABgIgHQgHgHgBgLQgEgmgSghQgLgWgZgWQgxgqhBAAQgpAAgqAVQhTArgFBsQAAALgIAHQgHAHgLAAg");
	this.shape_10.setTransform(93.5,44,0.914,0.914);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#020203").s().p("AhsBsQgtgsAAhAQAAg+AtguQAtgsA/gBQBAABAtAsQAtAuAAA+QAAA/gtAtQgtAuhAgBQg/ABgtgug");
	this.shape_11.setTransform(19.2,55.4,0.914,0.914);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#020203").s().p("AAAAVQgIgFgBgQQAAgPAJgFIAKgCIgBAtIgBAAQgEAAgEgCg");
	this.shape_12.setTransform(0.9,39.8,0.914,0.914);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#E22B2B").s().p("AsqEYQgGAAgDgGQgGgJAAgkIAChhQAAgtAxgrQBkhXD7AFQAOAAAIgLQBUh2BDg/QAigfAugGQDOgZDRAbQAkAEAjAKQB0AiBjA5QCbBZBHB7IAZAuQAdA5APAvIlRg9IiABLItIAZQggg2hAgVIg6gLQgdgCgjAOQhHAcghBQQgCAFgGAAIgBAAgACvi+QgLALAAATIAABRQAAAdAVAUQAUAVAdAAIDHAAQAXAAAPgIQAggPgFgqQgBgGgCgHQgMglhJgmQhQgqhQAAIgrAAQgUABgMANgAkXiSQgdAggVAlIgCAEQgLAcAMASQAHALAPAFQAEACAEAAIFKAAQAdAAAUgVQAVgUAAgdIAAg3QAAgdgVgUQgUgVgdAAIjQAAQgxAAg0A6g");
	this.shape_13.setTransform(77.1,25.6,0.914,0.914);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#1D1D1C").ss(3).p("Ai4AAIFxAA");
	this.shape_14.setTransform(162.4,41.5,0.661,0.914);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#59AE40").s().p("A7fDuQgoAAgcgcQgdgcAAgpIAAkZQAAgoAdgdQAcgcAoAAMA2/AAAQApAAAcAcQAcAdAAAoIAAEZQAAApgcAcQgcAcgpAAgA7QiQQgLAegNA8QgMA7gGAvIgBAOQAAAbAWAQQAKAIAHgLQBGhkAvg7QA4hJgLgWQgFgJgJAIQgbAdgtA8QgvA9ggAwQAMg9ARhMQAEgSABgOQAAgQgKgLQgEgGgEAAQgFAAgEAJgAbWiVQgHAAgdAEQgjAGgeAAQgLAAACAIQADAMAOAIQg+BggfBQQgGAQAFAHIAKASQAGAJAQgEQA+gRAbAAQAKAAgCgJQgIgUgfABQgZABggAJQAKgWATgkQApgLAeAAQAMAAgEgIQgHgVgfABIgVACQAmhFAOgVIAQgDQAqgIAVAAQANAAgEgIQgIgVgZAAIgCAAgAU2iVQgHAAgdAEQgjAGgdAAQgMAAADAIQACAMAOAIQg+BggfBQQgFAQADAHIALASQAGAJAQgEQA+gRAbAAQALAAgDgJQgIgUggABQgZABgfAJQAKgWATgkQAqgLAdAAQAMAAgEgIQgGgVgfABIgWACQAnhFANgVIAQgDQAqgIAVAAQAGAAADgCIAAABQAIAOARADQgbApgZAzQgYAvgHAcQgEAKAAAKQAAAOAIAIQAKAKAEgMQARgrAQggQAQASAuA9QAIAKAHgLQADgHAAgHQABgLgGgKQgMgYgZgdQAigJAegQQAdgSAQgWQAbglgPgjQgNgjgnABQgRABgdAJQgbAJgTADQgGABgCACQgIgVgZAAIgCAAgAOviVQgJAAgcAEQgiAGgfAAQgKAAABAIQAEAMANAIQg+BggfBQQgGAQAFAHIAKASQAHAJAPgEQA+gRAaAAQALAAgDgJQgHgUgfABQgZABgfAJQAJgWATgkQApgLAfAAQALAAgDgIQgHgVggABIgVACQAmhFAOgVIARgDQApgIAVAAQAMAAgDgIQgIgVgZAAIgBAAgAGTiVQgJAAgcAEQgiAGgfAAQgKAAABAIQAEAMANAIQg+BggfBQQgGAQAFAHIAKASQAHAJAPgEQA+gRAaAAQALAAgDgJQgHgUgfABQgaABgeAJQAJgWATgkQApgLAfAAQALAAgDgIQgHgVggABIgVACQAmhFAOgVIARgDQApgIAVAAIAEAAIAAACQAHAQASACQg3BTgSA5QgGASAAAJQAAAHALAPQAPAUARAAQAFAAAIgDQBCgWAvg3QAsg1AAgzQAAgZgKgQQgagrgoAGQgRADgUAJQgXALgPABIgDABQgIgVgZAAIgBAAgAjXiVQgIAAgcAEQgjAGgeAAQgLAAACAIQADAMAOAIQg+BgggBQQgFAQAEAHIAKASQAHAJAQgEQA9gRAbAAQALAAgDgJQgIgUgfABQgZABgfAJQAKgWATgkQApgLAeAAQAMAAgEgIQgHgVgfABIgWACQAnhFANgVIARgDQApgIAWAAQAMAAgDgIQgIgVgaAAIgBAAgAxkiVQgHAAgdAEQgiAGgeAAQgLAAACAIQACAMAOAIQg+BggfBQQgGAQAEAHIALASQAGAJAQgEQA+gRAbAAQAKAAgDgJQgHgUggABQgZABgeAJQAJgWATgkQAqgLAeAAQALAAgDgIQgIgVgeABIgWACQAnhFANgVIARgDQApgIAVAAQANAAgEgIQgIgVgZAAIgCAAgA2wiVQgHAAgdAEQgjAGgdAAQgLAAACAIQACAMAOAIQg+BggfBQQgGAQAEAHIALASQAGAJAQgEQA+gRAbAAQAKAAgCgJQgIgUggABQgZABgfAJQAKgWATgkQAqgLAdAAQAMAAgEgIQgHgVgeABIgWACQAnhFANgVIARgDQApgIAVAAQANAAgEgIQgIgVgZAAIgCAAgAK0BrQAHAKAHgLQAEgHAAgHQAAgLgGgKQgMgYgZgdQAigJAegQQAegSAPgWQAbglgOgjQgOgjgmABQgSABgcAJQgbAJgUADQgMACAFAIQAHAOARADQgaApgZAzQgYAvgIAcQgDAKAAAKQAAAOAIAIQAJAKAEgMQASgrAQggQAQASAuA9gA2vAFQgYAGgGAcQgDAIAAAKQAAAZAQAOQAQAQAdAAQAyAAAkg8QAPgZAZgyIAjhJQAIgSAAgPQAAgMgFgIQgIgOgJAOQgQAYg2BuQgZAxgQAYQgYAigVAAQgRAAAAgeQAAgRAJgcQAEgMgKAAIgFAAgAiLiSQgbArgeA7QghBAgPAnQgGAOAAAKQAAANAIAKQAKALAFgNQAYhEA1hZQgGAzABApIABAeQACAdATAKQAKAFAFgJQASgoAgg+QAfg6ASgdQAPgZAAgUQAAgJgEgHQgHgNgJALQgwBNgvBgQAFhPAHgsIACgUQABgTgTgNQgDgDgDAAQgGAAgEAHgAwYiSQgaArgeA7QgiBAgPAnQgFAOgBAKQAAANAJAKQAJALAGgNQAXhEA1hZQgFAzAAApIABAeQACAdAUAKQAJAFAFgJQATgoAfg+QAgg6ARgdQAPgZAAgUQAAgJgEgHQgHgNgIALQgxBNguBgQAEhPAIgsIACgUQAAgTgSgNQgEgDgDAAQgFAAgFAHgAoIiTQgUAbgmBIQgoBIgPAlQgFAPADAKQACAFAKANQAGAKARgEQA/gRAYAAQAMAAgEgJQgJgWgfACQgbADgcAHQANgdBJiDQAOgZAAgSQAAgJgEgIQgEgGgEAAQgDAAgFAFgAR4iSQgiAGgbAAQgLAAACAIQADAOANAHQgcAtgbAyQgaAygJAaQgFAPgBAKQAAAQAKAGQAKAHAEgKQAag4AQgeQAegHApgEQALgBgDgIQgGgXghACIgTADIAxhXQBBgMAQABQANAAgFgJQgIgXgdAAQgOAAgYAEgADDibQgRABghALQgfALgNABQgLABADAJQAIAPASADQgyBMgZBGQgHAQAAAJQAAAKAIALQAJALAMAGQAKAEALAAIAQgCQAUgEAUgKQAWgMAMgNQAQgQAAgVQAAgXgWgNQAngTAVgcQASgWAAgWQAAgigQgPQgNgMgTAAIgGABgAZDiVQgYAjgjBBQgjBBgQApQgFAPAAALQAAAOAHAIQAJAKAGgMQAbg8BIh/QAPgdAAgTQAAgKgDgHQgEgHgEAAQgFAAgFAHgApWiVQgZAjgiBBQgkBBgQApQgEAPAAALQgBAOAIAIQAJAKAFgMQAbg8BIh/QAQgdAAgTQAAgKgEgHQgDgHgFAAQgEAAgFAHgAsygMQgbAzgIAbQgCAIAAAIQAAAPAJAIQAIAJAFgLQAbg8AxhXQAdg0AAgSQAtgHATACQAOABgFgKQgIgXgjAAQgKAAgwAGQgwAGgUAAQgJAAACAIQAHAZAqAAIASgCQgbAqgbA2gABIBEQAIgXASglQAOAEAagFQAaACAAANQABAJgKALQgMAPgXAMQgVALgSACIgDAAQgKAAAEgOgAGbBMIACgMQAKgjA2hbQAOgYgCgSIAZgLQARgHAIAAQAKAAAFAJQAFAJAAAOQAAAqglAwQgqA3g/AYIgDABQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBgAWFg9QAOgcABgRIAQgGQAdgKAKAAQAJAAAEAJQAJAXgeAfQghAig6APgAKog9QAPgcAAgRIARgGQAdgKAJAAQAKAAAEAJQAIAXgeAfQghAig6APgACOhFQANgYgBgPQAtgQAKAAQAOAAABAOQgBAXgdAaQghAdgwAMg");
	this.shape_15.setTransform(360.4,34.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#1D1D1C").s().p("A7lCEQgVgQAAgbIABgOQAGgvAMg7QANg9ALgdQAHgQAKAMQAJAMAAAQQAAANgEATQgSBLgLA+QAfgxAvg8QAug9AbgcQAJgJAEAJQAMAXg4BIQgvA8hGBkQgEAGgFAAQgEAAgFgDgAYmCAIgLgSQgEgGAGgQQAfhRA+hfQgOgJgDgMQgCgIALAAQAeAAAjgGQAcgEAIAAQAbAAAIAWQADAIgMAAQgVAAgqAIIgQADQgOAVgmBEIAVgCQAfgBAHAUQAEAKgMAAQgeAAgpALQgTAjgKAWQAfgIAZgCQAggBAHAVQADAJgLAAQgagBg+ARIgJACQgJAAgEgHgASGCAIgLgSQgEgGAGgQQAfhRA+hfQgOgJgDgMQgCgIALAAQAeAAAjgGQAcgEAIAAQAbAAAIAVQACgCAFgBQAUgDAbgJQAdgJARgBQAmgBAOAkQAOAjgbAlQgPAVgeARQgdASgiAIQAZAeAMAXQAFALAAALQAAAHgEAHQgHAKgHgJQgug+gQgRQgQAggRAqQgFAMgJgJQgIgJAAgNQAAgKADgLQAIgbAYgxQAZgxAagpQgQgDgIgOIgBgBQgCACgGAAQgVAAgqAIIgQADQgOAVgmBEIAVgCQAfgBAHAUQAEAKgMAAQgeAAgpALQgTAjgKAWQAfgIAZgCQAggBAHAVQADAJgLAAQgagBg+ARIgJACQgJAAgEgHgAWlhZIgQAFQgBARgPAdIgdAxQA6gNAigjQAegfgJgWQgEgJgKAAQgJAAgdAKgAL+CAIgLgSQgEgGAGgQQAfhRA+hfQgOgJgDgMQgCgIALAAQAeAAAjgGQAcgEAIAAQAbAAAIAWQADAIgMAAQgVAAgqAIIgQADQgOAVgmBEIAVgCQAfgBAHAUQAEAKgMAAQgeAAgpALQgTAjgKAWQAfgIAZgCQAggBAHAVQADAJgLAAQgagBg+ARIgJACQgJAAgEgHgADiCAIgLgSQgEgGAGgQQAfhRA+hfQgOgJgDgMQgCgIALAAQAeAAAjgGQAcgEAIAAQAbAAAIAVIACAAQAQgCAXgKQATgJASgEQAogGAaArQAJAQAAAZQAAA0gsA0QguA4hCAWQgIADgGAAQgQAAgPgVQgLgOAAgIQAAgIAGgSQASg6A3hSQgTgDgGgPIgBgDIgDABQgVAAgqAIIgQADQgOAVgmBEIAVgCQAfgBAHAUQAEAKgMAAQgeAAgpALQgTAjgKAWQAfgIAZgCQAggBAHAVQADAJgLAAQgagBg+ARIgJACQgJAAgEgHgAIDhcIgZAKQACASgOAZQg2BbgKAjIgCAMQAAAFAGgCQA/gYAqg4QAlgwAAgpQAAgPgFgIQgGgJgJAAQgIAAgRAHgAmICAIgKgSQgEgGAFgQQAfhRA+hfQgNgJgDgMQgCgIALAAQAeAAAigGQAdgEAIAAQAaAAAIAWQAEAIgNAAQgVAAgpAIIgRADQgNAVgnBEIAWgCQAfgBAHAUQADAKgLAAQgeAAgqALQgTAjgJAWQAfgIAZgCQAfgBAIAVQADAJgLAAQgbgBg+ARIgJACQgIAAgFgHgA0UCAIgLgSQgEgGAGgQQAfhRA+hfQgOgJgDgMQgCgIALAAQAeAAAjgGQAcgEAIAAQAbAAAIAWQADAIgMAAQgVAAgqAIIgQADQgOAVgmBEIAVgCQAfgBAHAUQAEAKgMAAQgeAAgpALQgTAjgKAWQAfgIAZgCQAggBAHAVQADAJgLAAQgagBg+ARIgJACQgJAAgEgHgA5gCAIgLgSQgEgGAGgQQAfhRA+hfQgOgJgDgMQgCgIALAAQAeAAAjgGQAcgEAIAAQAbAAAIAWQADAIgMAAQgVAAgqAIIgQADQgOAVgmBEIAVgCQAfgBAHAUQAEAKgMAAQgeAAgpALQgTAjgKAWQAfgIAZgCQAggBAHAVQADAJgLAAQgagBg+ARIgJACQgJAAgEgHgAK1CCQgvg+gPgRQgQAggSAqQgEAMgJgJQgIgJAAgNQAAgKADgLQAIgbAYgxQAYgxAbgpQgRgDgIgOQgEgJAMgCQAUgDAbgJQAcgJARgBQAngBAOAkQAOAjgbAlQgQAVgdARQgeASgiAIQAZAeAMAXQAGALAAALQAAAHgEAHQgEAFgDAAQgEAAgDgEgALJhZIgRAFQAAARgPAdIgdAxQA6gNAhgjQAegfgJgWQgDgJgKAAQgKAAgcAKgA2/B3QgQgPAAgYQAAgLACgIQAHgcAYgFQAPgEgEAPQgJAcAAASQAAAeARAAQAVAAAYgjQAQgYAYgyQA3htAQgYQAJgNAIAOQAFAHAAANQAAAPgIARIgjBKQgZAxgQAaQgjA7gyAAQgdAAgQgPgAjxCBQgIgKAAgNQAAgLAFgOQAPgnAihAQAeg6AbgrQAHgMAJAHQASAOAAATIgCAUQgHArgFBQQAuhgAxhNQAIgMAIANQAEAIAAAIQAAAVgQAYQgRAdgfA7QggA9gTApQgEAJgKgFQgTgKgDgdIgBgeQAAgrAGgyQg1BagYBEQgDAHgEAAQgEAAgEgFgAx+CBQgIgKAAgNQAAgLAGgOQAPgnAihAQAeg6AagrQAHgMAKAHQASAOAAATIgCAUQgIArgFBQQAvhgAxhNQAIgMAHANQAEAIAAAIQAAAVgPAYQgSAdgfA7QggA9gSApQgFAJgJgFQgUgKgCgdIgBgeQAAgrAFgyQg1BagYBEQgCAHgFAAQgDAAgFgFgApuB/QgKgOgCgEQgEgLAGgOQAOglAohJQAnhIAUgaQAJgMAHANQAEAHAAAKQAAASgPAZQhICDgNAcQAcgHAbgCQAfgCAJAWQAEAJgMAAQgYgBg/ARIgJABQgKAAgEgGgAPtCCQgKgGAAgQQAAgKAFgQQAJgZAbg0QAagxAcgsQgMgHgDgOQgCgIALAAQAaAAAjgGQAYgEAOAAQAcAAAJAWQAEAJgMAAQgRAAhAALIgxBWIATgBQAggCAHAVQADAKgMABQgpADgeAIQgPAegaA4QgDAFgEAAQgDAAgEgCgABDCAQgMgGgJgLQgIgLAAgKQAAgJAGgQQAahGAyhMQgSgDgIgPQgEgJAMgBQAMAAAggLQAhgMAQgBQAYgCAOANQAQAQAAAhQAAAWgSAXQgUAcgnASQAWANAAAYQAAAUgQARQgMANgXALQgTAKgUAFIgRABQgLAAgJgEgABJBaQgFARANgCQATgDAVgLQAXgMAMgPQAJgKAAgJQAAgOgagCQgaAGgOgEQgTAlgHAWgACbhWQABAPgNAZIgdAwQAwgMAhgdQAdgaAAgWQAAgOgOAAQgKAAgtAPgAXYB/QgHgHAAgOQAAgLAFgPQAQgpAjhCQAjhAAYgkQAKgOAIAPQADAHAAAJQAAAUgPAcQhJB/gbA9QgCAGgEAAQgDAAgFgFgArBB/QgIgHAAgOQAAgLAFgPQAQgpAjhCQAjhAAZgkQAKgOAHAPQAEAHAAAJQAAAUgQAcQhIB/gbA9QgDAGgEAAQgDAAgEgFgAtOB/QgIgIAAgOQAAgJACgIQAIgaAag1QAcg1AagpIgRACQgqAAgHgaQgCgIAJAAQAUAAAwgFQAwgGAKAAQAjAAAIAWQAEALgNgCQgTgCgtAIQAAASgeA0QgwBWgbA8QgCAGgEAAQgEAAgEgEg");
	this.shape_16.setTransform(360.3,32.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,546.1,69.4), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.trykher1();
	this.instance.parent = this;
	this.instance.setTransform(76,540.8,1,1,0,0,0,65,65);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(11,475.8,130,130), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.logo = new lib.Symbol5();
	this.logo.name = "logo";
	this.logo.parent = this;
	this.logo.setTransform(76,28.8,1.07,1.067,0,0,0,73.8,27);

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,11.5,152,38.1);


(lib.bil = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol3();
	this.instance.parent = this;
	this.instance.setTransform(273.1,34.7,1,1,0,0,0,273.1,34.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,546.1,69.4);


// stage content:
(lib.reklamebanner12 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_96 = function() {
		/* Click to Go to Web Page
		Clicking on canvas or stage loads the specified URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
		
		canvas.onclick = function(event) {
		    window.open("http://www.google.com", "_blank");
		}
	}
	this.frame_115 = function() {
		/* Click to Go to Web Page
		Clicking on canvas or stage loads the specified URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
		
		canvas.onclick = function(event) {
		    window.open("http://www.google.com", "_blank");
		}
	}
	this.frame_191 = function() {
		//stop er en createJS som stopper tidslinjen
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(96).call(this.frame_96).wait(19).call(this.frame_115).wait(76).call(this.frame_191).wait(1));

	// GlobalCar
	this.logo = new lib.Symbol5();
	this.logo.name = "logo";
	this.logo.parent = this;
	this.logo.setTransform(80.7,433.6,0.074,0.074,180,0,0,74.4,27.7);
	this.logo._off = true;

	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(79,433,1,1,0,0,0,74.7,27.3);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.logo}]},97).to({state:[{t:this.instance}]},18).wait(77));
	this.timeline.addTween(cjs.Tween.get(this.logo).wait(97).to({_off:false},0).to({_off:true,regX:74.7,regY:27.3,scaleX:1,scaleY:1,rotation:0,x:79,y:433},18).wait(77));

	// text-nu
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFF02").s().p("Ag7H7QgggOAAgkQAAgMACgMQANg1BOh5QAJgMAIANQAFAIABAKQAAAQgNAXIgkBCQgYAtgHAaIgDASQAAATAOAAQAfAAAnhOQAuhZAphBQAIgNAIANQAFAIAAAJQgBAPgIATQgMAagcAzQgfA4gSAZQgfArgoAAQgNAAgLgEgACCH+QgJgCgFgIQgFgIAAgHQAAgIAFgGQAGgHAGAAQANAAAHAOQAGAOgKAOQgDAEgGAAIgFAAgAkQH5QgHgKAAgMQgBgLAGgNQAOgmAhg/QAdg5AagqQAHgLAIAHQATANgBATIgCATQgHAqgEBOQAsheAvhKQAJgMAHANQAEAHgBAJQABATgPAYQgRAcgfA6QgfA7gRAoQgEAJgKgFQgTgKgCgcIgBgdQAAgqAFgxQgzBYgYBCQgCAGgEAAQgDAAgFgEgACSHRQgIgHAAgNQAAgKAGgPQAMghAZgwQAagzAVgfQAKgPAHAPQAEAJAAAHQAAATgPAbQgxBXgZA5QgDAGgEAAQgDAAgEgEgAjjB9QgIgKAAgMQAAgLAFgNQAOgmAig+QAdg5AZgqQAHgLAJAHQASANAAATIgCATQgHAqgFBNQAthdAvhKQAIgMAIANQACAHAAAJQAAATgOAYQgRAcgeA5QgfA7gSAoQgEAJgKgFQgSgKgCgcIgCgdQAAgqAFgwQgzBXgXBCQgCAGgFAAQgDAAgEgEgAEvB7IgLgSQgDgKAFgOQAOgkAmhGQAmhGAUgZQAIgMAHANQADAHABAJQgBASgOAYQhFB/gNAbQAbgHAagCQAegCAJAVQADAJgLAAQgXAAg+AQIgIABQgJAAgFgGgABIB8QgMgGgJgLQgIgKAAgKQAAgIAGgQQAZhEAwhJQgRgDgHgPQgFgJAMAAQAMgBAfgLQAfgKARgCQAWgCAOANQAQAPAAAhQAAAVgRAWQgUAbgnARQAXANAAAXQAAAUgQAQQgMANgWALQgTAJgSAFIgRABQgKAAgJgEgABNBXQgFAQANgCQATgCAUgLQAWgLAMgPQAJgKgBgJQAAgNgZgCQgaAFgNgDQgSAkgHAVgACdhTQABAOgOAYIgbAvQAugMAggbQAdgaAAgVQAAgOgOAAQgKAAgrAPgADfB7QgHgHAAgOQAAgKAEgPQAQgoAig/QAig+AXgjQALgNAGAOQAEAHAAAJQAAASgPAcQhGB7gbA7QgCAGgEAAQgDAAgEgFgAkuB7QgGgHAAgOQgBgKAFgPQAPgoAjg/QAhg+AYgjQAKgNAHAOQAEAHgBAJQABASgPAcQhHB7gaA7QgCAGgEAAQgDAAgFgFgAnhBsQgKgOAAgIQAAgIAGgRQASg4A1hQQgTgCgGgPQgDgJALgCQAOgCAXgKQATgIARgDQAmgHAZAqQAKAQgBAYQAAAygqAzQgsA1hBAWQgHACgGAAQgPAAgQgTgAlnhZIgZAKQADARgNAYQg1BYgLAiIgBAMQAAAFAGgCQA+gYAog2QAjguABgoQAAgOgGgIQgFgJgJAAQgIAAgQAHgACGj/IgKgRQgEgHAGgPQAehOA7hdQgNgJgDgLQgCgIALAAQAdAAAhgGQAcgEAIAAQAZAAAJAVQADAIgMAAQgVAAgoAIIgQACQgNAVglBDIAVgDQAdgBAIAVQADAJgMAAQgdAAgoAKQgSAjgKAVQAfgIAYgCQAegBAIAUQADAJgLAAQgagBg8ARIgJABQgIAAgEgGgAEikIQgPgOAAgYQAAgKACgIQAHgbAXgFQAOgDgEAOQgJAbAAARQABAdAQAAQAVAAAXghQAQgXAXgxQA1hrAPgXQAJgNAIAOQAFAHgBAMQAAAOgHARIghBIQgZAxgPAZQgjA5gwAAQgcAAgQgPgAnBj+QgvgSAAg6QAAg6Aqg3QAmgvAogPQALgDANAAQAWAAAKALQAlARAAAwQAAAtgZAvQgXAogcAYQgfAbggAAQgOAAgNgFgAl2nUQggAWgZAnQgdAtAAAvQAAAsAYAAQAUAAAYgWQAagXAVgmQAbgyAAgrQAAgfgNgEIgGgCQgOAAgXAQgAgBkAIgLgSQgEgKAGgOQANgkAnhHQAlhGAUgZQAIgMAHANQADAHABAJQgBASgOAYQhFCAgNAbQAbgHAagCQAegCAJAVQADAJgLAAQgYAAg9AQIgIABQgJAAgEgGgAkCkHQgcgUAAgrQAAg6Avg4QAogwAogOQAOgFAPAAQARAAAKAIQAZASAAAZQAAAKgFAMIgPAlQgFAMgKgIQgOgMAAgPQgBgHAEgKQAQgogFgEQgJgKgkAXQglAZgaAnQgdAsAAAwQAAApAYAAQAPAAAUgPQATgQAOgaIgcAEQggACgKgWQgEgKALAAQASgBAdgFQAegEAJAAQAdgBAKAWQAEAKgNgBIgWABQAFAZgYAaQgWAWgTAFQgRAFgNAAQgYAAgRgNg");
	this.shape.setTransform(82.8,307.7);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(99).to({_off:false},0).wait(93));

	// bil
	this.instance_1 = new lib.bil("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(440.3,565.3,1,1,0,0,0,273.1,34.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(72).to({_off:false},0).wait(1).to({x:434.3},0).wait(1).to({x:428.2},0).wait(1).to({x:422.2},0).wait(1).to({x:416.1},0).wait(1).to({x:410.1},0).wait(1).to({x:404.1},0).wait(1).to({x:398},0).wait(1).to({x:392},0).wait(1).to({x:386},0).wait(1).to({x:379.9},0).wait(1).to({x:373.9},0).wait(1).to({x:367.8},0).wait(1).to({x:361.8},0).wait(1).to({x:355.8},0).wait(1).to({x:349.7},0).wait(1).to({x:343.7},0).wait(1).to({x:337.6},0).wait(1).to({x:331.6},0).wait(1).to({x:325.6},0).wait(1).to({x:319.5},0).wait(1).to({x:313.5},0).wait(1).to({x:307.4},0).wait(1).to({x:301.4},0).wait(1).to({x:295.4},0).wait(1).to({x:289.3},0).wait(1).to({x:283.3},0).wait(1).to({x:277.2},0).wait(1).to({x:271.3},0).wait(1).to({x:265.2},0).wait(1).to({x:259.2},0).wait(1).to({x:253.1},0).wait(1).to({x:247.1},0).wait(1).to({x:241},0).wait(1).to({x:235},0).wait(1).to({x:229},0).wait(1).to({x:222.9},0).wait(1).to({x:216.9},0).wait(1).to({x:210.9},0).wait(1).to({x:204.8},0).wait(1).to({x:198.8},0).wait(1).to({x:192.7},0).wait(1).to({x:186.7},0).wait(1).to({x:180.7},0).wait(1).to({x:174.6},0).wait(1).to({x:168.6},0).wait(1).to({x:162.5},0).wait(1).to({x:156.5},0).wait(1).to({x:150.5},0).wait(1).to({x:144.4},0).wait(1).to({x:138.4},0).wait(1).to({x:132.3},0).wait(1).to({x:126.3},0).wait(1).to({x:120.3},0).wait(1).to({x:114.2},0).wait(1).to({x:108.2},0).wait(1).to({x:102.1},0).wait(1).to({x:96.1},0).wait(1).to({x:90.1},0).wait(1).to({x:84},0).wait(1).to({x:78},0).wait(1).to({x:71.9},0).wait(1).to({x:65.9},0).wait(1).to({x:59.9},0).wait(1).to({x:53.8},0).wait(1).to({x:47.8},0).wait(1).to({x:41.7},0).wait(1).to({x:35.7},0).wait(1).to({x:29.7},0).wait(1).to({x:23.6},0).wait(1).to({x:17.6},0).wait(1).to({x:11.5},0).wait(1).to({x:5.5},0).wait(1).to({x:-0.5},0).wait(1).to({x:-6.6},0).wait(1).to({x:-12.6},0).wait(1).to({x:-18.6},0).wait(1).to({x:-24.7},0).wait(1).to({x:-30.7},0).wait(1).to({x:-36.8},0).wait(1).to({x:-42.8},0).wait(1).to({x:-48.8},0).wait(1).to({x:-54.9},0).wait(1).to({x:-60.9},0).wait(1).to({x:-67},0).wait(1).to({x:-73},0).wait(1).to({x:-79},0).wait(1).to({x:-85.1},0).wait(1).to({x:-91.1},0).wait(1).to({x:-97.2},0).wait(1).to({x:-103.2},0).wait(1).to({x:-109.2},0).wait(1).to({x:-115.3},0).wait(1).to({x:-121.3},0).wait(1).to({x:-127.4},0).wait(1).to({x:-133.4},0).wait(1).to({x:-139.4},0).wait(1).to({x:-145.5},0).wait(1).to({x:-151.5},0).wait(1).to({x:-157.6},0).wait(1).to({x:-163.6},0).wait(1).to({x:-169.6},0).wait(1).to({x:-175.7},0).wait(1).to({x:-181.7},0).wait(1).to({x:-187.8},0).wait(1).to({x:-193.8},0).wait(1).to({x:-199.8},0).wait(1).to({x:-205.9},0).wait(1).to({x:-211.9},0).wait(1).to({x:-217.9},0).wait(1).to({x:-224},0).wait(1).to({x:-230},0).wait(1).to({x:-236.1},0).wait(1).to({x:-242.1},0).wait(1).to({x:-248.2},0).wait(1).to({x:-254.2},0).wait(1).to({x:-260.2},0).wait(1).to({x:-266.3},0).wait(1).to({x:-272.3},0).wait(1).to({x:-278.4},0).wait(1));

	// tryg-her
	this.instance_2 = new lib.Symbol4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(80.1,342.5,0.6,0.6,0,0,0,76,302.9);
	this.instance_2._off = true;

	this.instance_3 = new lib.trykher();
	this.instance_3.parent = this;
	this.instance_3.setTransform(80,156.8,1,1,0,0,0,69.8,69.8);
	new cjs.ButtonHelper(this.instance_3, 0, 1, 1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#33CC33").s().p("AE/E4QgcAAgOgIQgOgIgHgUQgDgKgDgVIgCgZQgDgVgRAAIgHAAIAABRQABANADAEQADADAQAAIAAAMIh9AAIAAgMQAPAAADgDQADgEAAgNIAAitQAAgNgDgEQgDgDgPgBIAAgMICOAAQAoAAARAJQAYANAAAjQAAAYgRAQQgUAQglACIAAACQAiAGARASQANAOAEAXQAGAfAFAIQAEAGANADIAAAMgADgBbQgCADgBAHIAABVIAIAAQAgAAABgxQAAgwgbAAQgJAAgCACgAhkE4IAAgMQAQAAADgDQADgEABgNIAAitQgBgNgDgEQgDgDgQgBIAAgMIDCAAIAABGIgOAAQgRgngGgIQgIgHgVAAIgNAAQgIAAgCACQgBACAAAIIAABRIAMAAQAQAAAGgFQAFgFAIgaIAPAAIAABYIgPAAQgJgagEgFQgGgFgQAAIgMAAIAABNQAAAPAEACQADAEAUAAQAUAAAKgJQAMgLAVgqIAOAAIgHBNgAjsE4IAAgMQANAAADgCQACgDAAgMIAAhYIg0AAIAABYQAAAMADACQACADANAAIAAAMIh6AAIAAgMQAOAAAEgDQAEgDgBgLIAAizQABgMgEgCQgDgDgPgBIAAgMIB6AAIAAAMQgNABgCADQgDACAAAMIAABMIA0AAIAAhMQAAgMgCgCQgDgDgNgBIAAgMIB7AAIAAAMQgQABgDADQgEACAAAMIAACzQAAAMAEACQADADAQAAIAAAMgAGohJQgcgBgPgHQgOgHgJgPQgPgagVg4IgBAAIAABPQAAANAEAEQADADAQAAIAAANIh/AAIAAgNQAPAAAEgDQADgEAAgNIAAisQAAgOgDgDQgDgDgMgBQgJABgEACQgFACgFAJQgcA6gUA0QgDAIAAAJIAAA1QAAANAEADQAEADAVAAIAAANIiIAAIAAgNQAUAAAEgDQAEgDAAgNIAAgzQAAgJgDgHQgihNgVglQgFgIgEgCQgDgCgKgCIAAgLICEAAIAAALIgRADQgHABAFAKIApBeIAAAAQASguAOguQAEgNgIAAIgRgDIAAgLIC/AAIAAALQgPABgEAEQgEADAAAOIAABTIABAAQAOgNAdgjQAdgjAGgLQADgHgIgBIgSgDIAAgLIBZAAIAAALQgZAEgNALQgSAOghAkQANAbAUAmQAYApASAYQAMAQANAHIgCALgAgxhJQgcgBgOgHQgOgJgHgTQgCgLgDgUIgDgaQgDgUgQAAIgHAAIAABQQAAANAEAEQADADAQAAIAAANIh+AAIAAgNQAPAAAEgDQADgEAAgNIAAisQAAgOgDgDQgEgEgPgBIAAgLICPAAQAoAAARAJQAYANAAAiQgBAYgRAQQgTARglABIAAACQAhAHARARQANAOAFAYQAFAfAFAHQAFAHANACIAAANgAiQknQgCADAAAIIAABVIAHAAQAhAAAAgyQAAgwgbAAQgIAAgDACgAm3hJIAAgNQATAAAFgDQAHgEgBgNIAAi9IgKAAQgRAAgFAIQgHAJgMAoIgQAAIAAhJIDZAAIAABJIgQAAQgMgogHgJQgGgIgQAAIgLAAIAAC9QAAANAGAEQAGADAUAAIAAANg");
	this.shape_1.setTransform(81,156.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFF00").s().p("ACkDyIAAhVQAAgHADgDQACgCAIAAQAbAAAAAwQAAAxghAAgAjLiPIAAhVQAAgIACgDQADgCAIAAQAbAAAAAwQAAAyghAAg");
	this.shape_2.setTransform(86.7,151.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_2}]},59).to({state:[{t:this.instance_2}]},18).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.instance_3}]},1).wait(96));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(59).to({_off:false},0).wait(18).to({regX:75.9},0).wait(1).to({regY:540.8,scaleX:0.63,scaleY:0.63,y:467},0).wait(1).to({scaleX:0.65,scaleY:0.65,y:448.7},0).wait(1).to({scaleX:0.68,scaleY:0.68,y:430.5},0).wait(1).to({scaleX:0.71,scaleY:0.71,x:80,y:412.2},0).wait(1).to({scaleX:0.73,scaleY:0.73,y:394},0).wait(1).to({scaleX:0.76,scaleY:0.76,y:375.8},0).wait(1).to({scaleX:0.78,scaleY:0.78,y:357.5},0).wait(1).to({scaleX:0.81,scaleY:0.81,x:79.9,y:339.3},0).wait(1).to({scaleX:0.84,scaleY:0.84,y:321.1},0).wait(1).to({scaleX:0.86,scaleY:0.86,y:302.8},0).wait(1).to({scaleX:0.89,scaleY:0.89,y:284.5},0).wait(1).to({scaleX:0.92,scaleY:0.92,y:266.3},0).wait(1).to({scaleX:0.94,scaleY:0.94,y:248.1},0).wait(1).to({scaleX:0.97,scaleY:0.97,y:229.8},0).wait(1).to({scaleX:1,scaleY:1,y:211.6},0).wait(1).to({scaleX:1.02,scaleY:1.02,x:79.8,y:193.3},0).wait(1).to({scaleX:1.05,scaleY:1.05,y:175},0).wait(1).to({scaleX:1.07,scaleY:1.07,x:79.9,y:156.8},0).to({_off:true},1).wait(96));

	// text-2
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFF00").s().p("AAuQ/QgjgSgcggQgKgMAOgFIAOgBQAYAAAPAMQAyApAgAAQASAAAIgIQALgLgLgKQgtgbgVgRQgogeAAggQAAguAtgtQAkglAqgSQAUgJATAAQARAAANALQAUASAHAZQAFAVgUAeQgJAMgZAqQgIAOgLgMQgMgMAAgPQAAgVAXgfQAbgogIgFQgHgFgVAJQgVAKgXASQg5AugCAnQgBAVAlAYQATANAgASQAPALAAAOQAAARgUAXQgWAagtAAQgeAAgfgQgAi+RIQg8gWAAhJQAAhIA2hFQAvg7AygSQAOgFAQAAQAbAAAOAPQAsAUAAA9QAAA4gfA7QgbAygjAeQgnAhgpAAQgRAAgQgGgAhgM9QgoAcggAwQglA5AAA6QAAA3AgAAQAYAAAegbQAhgdAagvQAig/AAg2QAAgmgQgGIgIgCQgSAAgcAUgAl3J0QgIgLAAgPQAAgSAag9QgLgGgFgJQgHgNASABIAQACQA7h6Ang4QAMgPAJAQQAEAIAAAMQAAAZgQAfIg2BhIBVgNQA9h6AigtQANgRAIASQAFAKAAAJQAAAZgUAhIg1BgQAOAHAEAPQACALgOgCIgXgCIgxBmQgDAHgFAAQgFABgEgGQgJgNAAgNQAAgLAHgUIASgqQhOAKgIAAIgrBeQgDAGgGABIgBAAQgFAAgEgFgACoJpQgjgSgdggQgKgMAOgFIAPgBQAYAAAPAMQAyApAgAAQASAAAIgIQALgLgLgKQgtgbgVgRQgogeAAggQAAguAtgtQAkglAqgSQAUgJATAAQARAAANALQAUASAHAZQAFAVgUAeQgJAMgZAqQgIAOgLgMQgMgMAAgPQAAgVAXgfQAbgogIgFQgHgFgVAJQgVAKgXASQg5AugCAnQgBAVAlAYQATANAgASQAPALAAAOQAAARgUAXQgWAagtAAQgeAAgfgQgAhEJyQg8gWAAhJQAAhIA2hFQAvg7AxgSQAOgFAQAAQAbAAAOAPQAtAUAAA9QAAA4ggA7QgbAygjAeQgnAhgoAAQgRAAgQgGgAAZFnQgnAcggAwQglA5AAA6QAAA3AgAAQAYAAAdgbQAhgdAagvQAig/AAg2QAAgmgQgGIgIgCQgSAAgcAUgAA5CZQgMgQgCgFQgFgNAHgSQARgsAxhYQAvhXAYghQALgOAIAQQAFAJAAALQAAAWgRAeQhXCfgRAiQAigIAhgDQAlgDALAbQAFALgPAAQgdAAhMAUIgLABQgMAAgFgIgAjoCbQgPgHgLgOQgKgNAAgMQAAgKAIgUQAfhVA8hcQgWgDgJgTQgFgLAPgBQAPgBAmgNQAogNAUgCQAcgDASAQQATATAAApQAAAagVAcQgZAhgwAXQAbAQAAAcQAAAZgTAUQgPAQgbAOQgYAMgXAFIgVACQgNAAgLgFgAjhBtQgHAUARgCQAWgDAagNQAcgPAPgSQAKgNAAgLQAAgQgfgDQggAHgRgFQgWAtgJAbgAh+hoQABASgQAeIgjA6QA6gOAogjQAkggAAgbQAAgRgRAAQgMAAg3ATgAgrCaQgJgJAAgRQAAgNAGgSQATgyAqhPQAqhOAegsQAMgRAJASQAFAJAAALQAAAXgTAjQhYCaggBJQgDAIgEAAQgEAAgGgGgAAek5QgJgMAAgQQAAgNAGgRQASgvAphPQAlhGAgg1QAIgOAMAJQAWARAAAXIgDAYQgJA0gGBiQA4h1A8heQAKgOAJAQQAEAJAAAKQAAAZgSAeQgWAjglBIQgnBKgWAyQgGAKgLgGQgYgMgDgjIgBgkQAAg0AGg9Qg/BtgeBSQgDAJgFAAQgEAAgGgGgAg+k7QgJgJAAgRQAAgNAGgSQATgyArhQQAphOAegsQAMgRAJASQAFAJAAALQAAAXgTAjQhXCbghBJQgDAIgEAAQgEAAgGgGgAkelOQgNgSAAgJQAAgKAHgWQAXhGBChlQgXgDgHgTQgEgLANgCQASgCAcgNQAYgKAWgEQAvgIAgA0QALATAAAfQAAA+g1BBQg4BDhQAbQgJADgIAAQgTAAgTgYgAiGpGIgeANQACAWgQAdQhCBvgNArIgCAPQAAAGAHgDQBNgdAzhDQAsg7AAgzQAAgRgGgKQgHgLgLAAQgKAAgUAIgAiEsQIgNgWQgFgIAHgTQAmhiBKh0QgQgKgEgPQgCgKAOAAQAkAAApgHQAigFAKAAQAgAAAKAaQADAKgOAAQgaAAgyAKIgUADQgQAaguBTIAagCQAlgCAIAaQAFALgPAAQgjAAgyANQgXArgMAbQAmgKAegCQAlgCAJAZQAEALgNAAQgfAAhMAUQgGACgEAAQgLAAgFgIgAA+sbQgTgSAAgdQAAgNADgKQAJgiAcgGQATgFgGATQgLAhAAAWQAAAkAWAAQAYAAAegqQAUgdAdg8QBBiGAUgdQALgQAKARQAGAJAAAPQAAASgKAVIgqBZQgeA9gTAgQgrBHg9AAQgjAAgUgSgAkusSQgMgQgCgFQgFgNAHgSQARgsAxhZQAvhXAYghQALgOAIAQQAFAJAAALQAAAWgRAeQhXCggRAiQAigIAhgDQAlgDALAbQAFALgPAAQgdAAhMAUIgLABQgMAAgFgIg");
	this.shape_3.setTransform(82.1,264.8);
	this.shape_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(23).to({_off:false},0).to({_off:true},57).wait(112));

	// text-1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFF00").s().p("An3I0QgbgIgXgSQgIgIAIgEIALgDQAQgDANAHQAnAWAWgEQAMgDAFgGQAGgJgJgFQgigOgRgJQgfgQgEgWQgFgfAZglQAVgeAbgSQAMgIANgCQAMgCAKAGQARAKAHAQQAGAOgKAXQgFAKgMAgQgDAKgKgGQgKgHgCgLQgCgOAMgYQAOgfgGgDQgGgDgNAJQgNAJgOAQQgiAmAEAcQACAOAcAMQAPAHAXAIQAMAGACAKQACALgLATQgLAUggAGIgOABQgOAAgQgFgAl7IkQgIgGgCgMQgBgIABgJQACgYANgsQAOgsAQgnQgQgBgHgLQgFgHAKgCQANgEAYgOQATgKARgEQAigIAPAdQAPAcgPAiQgKAYgWAVQgYAXgeAKQgOAEgJgCQgNAogHAgQgBAFgEAAIgFgBgAkQFNQgIACgXANIgNAGQACAPgIAZIgSAyQAtgTAYgkQAUgfgJgUQgDgFgGAAIgDAAgAjlIIQgFgHgBgEQgCgKADgPIAFgTQgIgEgEgGQgFgIALgBIANAAQAPgqAWgsQAagyAWgaQAJgLAJAJQAFAFAFAHQAEAHABAFQABAHgCAIQgGAyAAAzQALADAHAMQADAHgJAAIgMAAQABAfADAWQACAJgMgDQgPgEgFgaIgDgXIgYAGQgbAIgJABIgQA0QgCAGgEAAIgCAAQgCAAgDgDgAi9G2IAwgOQgCg0AHgnQgeA0gXA1gAhRHwQgIgHgCgLQgCgJADgMQAGgjATg7QARg1APgoQAEgLAKAFQARAJACAQIABAQQAAAlAIBFQAYhYAehHQAFgMAIAKQAEAGACAHQADARgKAXQgKAbgSA2QgRA4gKAlQgCAIgJgDQgRgGgGgYIgFgYQgGgkgDgrQgfBTgKA8QgBAHgFAAQgCAAgEgDgABKHUQgHgGgCgMQgCgJACgNQAHgkAUg9QAUg7APghQAGgOAJAMQAEAFABAIQADAQgJAaQgqB1gNA3QgBAGgEAAQgDAAgEgCgACLHJIgLgOQgFgFADgOQAOhIAlhZQgNgFgEgKQgDgGAKgCQAYgEAdgKQAWgIAHgBQAWgEALARQADAGgKACQgSADghANIgNAEQgIAUgWBAIARgGQAagFAJAQQAFAIgKACQgZAEghAPQgLAhgFATQAZgLAVgGQAagFAJAQQAEAHgKACQgWADgxAXQgGADgFAAQgEAAgEgDgAEJGzQgIgHgCgLQgCgJADgMQAGgjATg7QARg1APgoQAEgLAKAFQARAJADAQIABAQQAAAlAIBFQAYhYAehHQAFgMAIAKQAEAGACAHQADARgKAXQgKAbgSA2QgRA4gKAlQgCAIgJgDQgSgGgGgYIgFgYQgGgkgDgrQgfBTgKA8QgBAHgFAAQgCAAgEgDgAG7GQQgFgGgBgGQgBgJAFgHQAFgHAIABQAIACAGAIQADAFABAFQABAIgEAGQgEAGgIAAQgIAAgGgGgAHLFrQgIgGgCgLQgBgIACgIQAGgWAfgbQAdgZAJghQAEgPgCgMQgCgOgKABQgMACgNAVQgNAUgIAcQgEANgIgJQgGgGgCgJQgCgOAHgRQAHgTAOgMQANgMAQgDQANgCANAFQAWAKAEAYQADAPgFASQgJAeguAmQgaAWgCAhQgBAHgEAAQgDAAgEgDgApQD3QgJgDgCgOQgCgIACgOQAEgXAPguQAOguARgpQgMgFgEgLQgDgGAJgBQAWgEAcgLQAUgHAMgCQAXgEALARQAFAHgLACQgOADg0ATIgcBPIAQgFQAbgGAIASQAEAHgJACQgiAKgYAKIgWBPQgCAFgEAAIgFgBgAnRDfIgLgNQgFgFADgOQAOhJAlhYQgNgGgEgJQgDgHAKgCQAYgEAdgJQAWgHAHgBQAWgFALARQABgDAEgBQARgFAVgMQAXgLANgDQAggIARAcQARAagRAjQgKAVgWATQgWATgbAMQAZAVANARQAHAJACAIQABAGgDAHQgEAKgHgHQgwgtgQgMQgJAdgIAmQgCALgJgHQgIgGgCgLQgBgIABgKQADgYAMgsQANgtARgmQgPAAgIgLIgBgBQgBACgGABQgSADghANIgNAFQgIAUgWA/IARgFQAagGAJARQAFAHgKACQgZAEghAQQgLAggFAUQAZgMAVgFQAagGAJARQAEAHgKABQgWAEgxAXQgGADgFAAQgEAAgEgEgAjjgOQgHABgXANIgNAGQACAOgJAZIgQAvQAugUAXgiQAVgfgLgQQgEgGgGAAIgDABgAi3CtQgIgFgCgMQgBgJACgNQAHglAUg9QATg6APghQAHgNAIALQAEAGABAHQADAQgJAaQgpB1gOA2QgBAHgEAAQgDAAgDgDgAh2CiIgMgNQgEgFACgOQAOhJAmhXQgNgGgEgJQgDgHAJgCQAZgEAcgKQAXgHAHgBQAVgFAKARQAEAHgKABQgRADghANIgOAFQgIAUgWA+IASgFQAagGAIARQAFAHgKACQgZAEghAQQgLAggEAUQAYgMAVgFQAagGAKARQADAHgJABQgWAEgyAXQgGADgEAAQgFAAgDgEgABRB+QgIgFgCgMQgBgJACgNQAHglAUg8QATg7APghQAHgNAIALQAEAGABAHQADAQgJAaQgpB1gOA2QgBAHgEAAQgDAAgDgDgAprheQgbgIgXgTQgIgHAIgFIALgDQAQgCAMAGQAnAWAWgEQANgCAEgGQAHgJgJgGQgjgOgRgIQgegQgEgWQgGggAaglQAUgdAbgSQANgIANgCQAMgCAKAFQAQALAHAPQAHAPgLAXQgFAJgMAgQgDALgJgHQgKgHgCgKQgDgPANgYQANgfgGgDQgFgCgNAJQgOAJgNAPQgiAnADAbQACAOAcANQAPAHAYAIQAMAFACAKQACAMgLASQgMAVgfAFIgOABQgOAAgQgEgAnwhtQgHgHgCgKQgBgJABgNQACgWAWhHQAWhHALgYQAGgMAJAKQAFAGABAJQADARgHAVIgTAzQBHhNAZgtQADgEADABQAEAAACAEQAIAOgNAaQgTAmhHBJQAXAZAJANQAHALACAKQABAJgEAJQgDAEgDABQgEAAgDgEQgcgkgYgZQgMAngIAjQgCAIgEAAQgCAAgEgEgAljiJQgGgHAAgEQgCgKADgPIAFgTQgIgEgEgGQgGgIAMgBIAMAAQAPgqAXgsQAZgyAWgaQAJgLAJAJQAGAFAEAHQAEAHABAFQACAHgCAIQgHAyAAAzQAMADAHAMQADAHgJAAIgNAAQACAfADAWQACAJgMgDQgPgEgFgaIgEgXIgXAGQgbAIgKABIgQA0QgCAGgEAAIgBAAQgDAAgCgDgAk8jbIAxgOQgCg0AGgnQgeA0gXA1gAjLijIgMgNQgFgIADgNQAHghAWhDQAWhCANgZQAFgMAIAKQAEAGABAIQADAPgIAXQgpB4gHAaQAXgKAWgGQAZgGALARQAFAHgKACQgVADgyAXQgFACgFAAQgGAAgEgDgAgCjUQgLgKgBgGQgBgHABgQQAIg0AghNQgQABgHgMQgDgHAHgEQANgDASgMQAOgLAPgFQAggLAcAgQAKAMAEAVQAHArgdAzQgeA1g0AcQgGAEgFABIgEAAQgLAAgNgNgABbmaQgGABgNAIIgUANQAFAOgIAXQggBUgDAfIgBALQABAEAFgDQAygdAag1QAYgugGgjQgCgMgGgGQgFgGgGAAIgDABgAC1jkQgegGgFgfQgCgKAAgLQAEgwAxh0QAGgMAJAKQAGAGABAIQADAOgIAWIgWA/QgOAqgCAXIABARQADAQAMgCQAbgFAWhJQAahUAZg+QAFgMAJAKQAFAFABAIQADANgFASQgGAZgQAvQgTA2gMAYQgUAqgjAGIgKAAIgLgBgAGDkKQgHgGgCgMQgCgIABgJQADgYANgsQANgsAQgnQgPgBgHgLQgGgHALgCQANgEAYgOQASgKASgEQAigIAPAdQAPAcgPAiQgKAYgWAVQgYAXgeAKQgOAEgJgCQgNAogHAgQgCAFgDAAIgGgBgAHunhQgIACgXANIgMAGQACAPgJAZIgSAyQAugTAXgkQAUgfgJgUQgCgFgHAAIgDAAgAIZkmQgFgHgBgFQgCgKADgOIAFgUQgIgEgEgFQgFgJALAAIANgBQAPgpAWgsQAagzAWgaIAEgEIgBgFQgBgFABgHQAEgNANgCQAIgCAIAGQAHAGACAHQABAHgDAJQgEAMgLACQAEAGABAGQABAHgCAHQgGAyAAAzQALADAHANQADAGgJAAIgMABQABAeADAWQACAKgMgDQgPgFgFgZIgDgXIgYAGQgbAIgJABIgQA0QgCAFgEABIgCAAQgCAAgDgDgAJBl4IAwgOQgCg1AHgnQgeA0gXA2gAKKojQgBAGABAEIABAEQACgBACgGQADgIgBgFIgBgCQgEABgCAHg");
	this.shape_4.setTransform(80.4,75.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_4).to({_off:true},72).wait(120));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(93,318.7,134.9,113.8);
// library properties:
lib.properties = {
	id: 'E6C03D09EB394282A55BCD6E8C12A5DB',
	width: 160,
	height: 600,
	fps: 24,
	color: "#66CCFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['E6C03D09EB394282A55BCD6E8C12A5DB'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;